#!/bin/bash
# Run the script as ./launch_debug "PACKAGE_NAME" "ACTIVITY_NAME"
PACKAGE_NAME=$1
ACTIVITY_NAME=$2

LLDB_PORT=10000
JDB_PORT=9999

DEVICE_ID=$(cat .android_dbg/device_id)

SCRIPT_PATH=$(cd $(dirname "${BASH_SOURCE:-$0}") && pwd)
source $SCRIPT_PATH/lib

# Launch package in debug mode
launch_package -D

echo "> Copying lldb-server"
adb shell run-as $PACKAGE_NAME "cp -f /data/local/tmp/lldb-server /data/user/0/$PACKAGE_NAME"

# Start lldb server
start_lldb_server

wait_for_process

# Forward
adb forward tcp:$LLDB_PORT tcp:$LLDB_PORT
adb forward tcp:$JDB_PORT jdwp:$PID

mkdir -p .android_dbg
echo $JDB_PORT >.android_dbg/jdb_port
echo $LLDB_PORT >.android_dbg/lldb_port

